//
// Created by Cale on 5/20/2022.
//

#ifndef HSV_MAPPER_CONSTS_H
#define HSV_MAPPER_CONSTS_H

#define COMP_FLAGS_UNREADABLE 0x1;
#define GLAD_INIT_FAILURE 0x2;
#define GLFW_INIT_FAILURE 0x3;
#define GLFW_WINDOW_INIT_FAILURE 0x4;
#define FRAMEBUFFER_CREATION_FAILURE 0x5;

#endif //HSV_MAPPER_CONSTS_H
