# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /mnt/c/Users/Cale/cmake-3.25.0-linux-x86_64/bin/cmake

# The command to remove a file.
RM = /mnt/c/Users/Cale/cmake-3.25.0-linux-x86_64/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Cale/CLionProjects/HSV_Mapper

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Cale/CLionProjects/HSV_Mapper

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/mnt/c/Users/Cale/cmake-3.25.0-linux-x86_64/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/mnt/c/Users/Cale/cmake-3.25.0-linux-x86_64/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/mnt/c/Users/Cale/cmake-3.25.0-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/mnt/c/Users/Cale/cmake-3.25.0-linux-x86_64/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/mnt/c/Users/Cale/cmake-3.25.0-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/mnt/c/Users/Cale/cmake-3.25.0-linux-x86_64/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/mnt/c/Users/Cale/cmake-3.25.0-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/mnt/c/Users/Cale/cmake-3.25.0-linux-x86_64/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Cale/CLionProjects/HSV_Mapper/CMakeFiles /mnt/c/Users/Cale/CLionProjects/HSV_Mapper//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Cale/CLionProjects/HSV_Mapper/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hsv_mapgen

# Build rule for target.
HSV_Mapper: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HSV_Mapper
.PHONY : HSV_Mapper

# fast build rule for target.
HSV_Mapper/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/build
.PHONY : HSV_Mapper/fast

#=============================================================================
# Target rules for targets named glad

# Build rule for target.
glad: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glad
.PHONY : glad

# fast build rule for target.
glad/fast:
	$(MAKE) $(MAKESILENT) -f glad/CMakeFiles/glad.dir/build.make glad/CMakeFiles/glad.dir/build
.PHONY : glad/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f glfw-3.3.6/CMakeFiles/uninstall.dir/build.make glfw-3.3.6/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f glfw-3.3.6/src/CMakeFiles/update_mappings.dir/build.make glfw-3.3.6/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f glfw-3.3.6/src/CMakeFiles/glfw.dir/build.make glfw-3.3.6/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

src/Texture.o: src/Texture.cpp.o
.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i
.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s
.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/VertexBuffer.o: src/VertexBuffer.cpp.o
.PHONY : src/VertexBuffer.o

# target to build an object file
src/VertexBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/src/VertexBuffer.cpp.o
.PHONY : src/VertexBuffer.cpp.o

src/VertexBuffer.i: src/VertexBuffer.cpp.i
.PHONY : src/VertexBuffer.i

# target to preprocess a source file
src/VertexBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/src/VertexBuffer.cpp.i
.PHONY : src/VertexBuffer.cpp.i

src/VertexBuffer.s: src/VertexBuffer.cpp.s
.PHONY : src/VertexBuffer.s

# target to generate assembly for a file
src/VertexBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/src/VertexBuffer.cpp.s
.PHONY : src/VertexBuffer.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

utils/config_utils.o: utils/config_utils.cpp.o
.PHONY : utils/config_utils.o

# target to build an object file
utils/config_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/utils/config_utils.cpp.o
.PHONY : utils/config_utils.cpp.o

utils/config_utils.i: utils/config_utils.cpp.i
.PHONY : utils/config_utils.i

# target to preprocess a source file
utils/config_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/utils/config_utils.cpp.i
.PHONY : utils/config_utils.cpp.i

utils/config_utils.s: utils/config_utils.cpp.s
.PHONY : utils/config_utils.s

# target to generate assembly for a file
utils/config_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/utils/config_utils.cpp.s
.PHONY : utils/config_utils.cpp.s

utils/load_shader.o: utils/load_shader.cpp.o
.PHONY : utils/load_shader.o

# target to build an object file
utils/load_shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/utils/load_shader.cpp.o
.PHONY : utils/load_shader.cpp.o

utils/load_shader.i: utils/load_shader.cpp.i
.PHONY : utils/load_shader.i

# target to preprocess a source file
utils/load_shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/utils/load_shader.cpp.i
.PHONY : utils/load_shader.cpp.i

utils/load_shader.s: utils/load_shader.cpp.s
.PHONY : utils/load_shader.s

# target to generate assembly for a file
utils/load_shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/utils/load_shader.cpp.s
.PHONY : utils/load_shader.cpp.s

utils/log_utils.o: utils/log_utils.cpp.o
.PHONY : utils/log_utils.o

# target to build an object file
utils/log_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/utils/log_utils.cpp.o
.PHONY : utils/log_utils.cpp.o

utils/log_utils.i: utils/log_utils.cpp.i
.PHONY : utils/log_utils.i

# target to preprocess a source file
utils/log_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/utils/log_utils.cpp.i
.PHONY : utils/log_utils.cpp.i

utils/log_utils.s: utils/log_utils.cpp.s
.PHONY : utils/log_utils.s

# target to generate assembly for a file
utils/log_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/utils/log_utils.cpp.s
.PHONY : utils/log_utils.cpp.s

utils/parse_utils.o: utils/parse_utils.cpp.o
.PHONY : utils/parse_utils.o

# target to build an object file
utils/parse_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/utils/parse_utils.cpp.o
.PHONY : utils/parse_utils.cpp.o

utils/parse_utils.i: utils/parse_utils.cpp.i
.PHONY : utils/parse_utils.i

# target to preprocess a source file
utils/parse_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/utils/parse_utils.cpp.i
.PHONY : utils/parse_utils.cpp.i

utils/parse_utils.s: utils/parse_utils.cpp.s
.PHONY : utils/parse_utils.s

# target to generate assembly for a file
utils/parse_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/utils/parse_utils.cpp.s
.PHONY : utils/parse_utils.cpp.s

utils/print_help.o: utils/print_help.cpp.o
.PHONY : utils/print_help.o

# target to build an object file
utils/print_help.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/utils/print_help.cpp.o
.PHONY : utils/print_help.cpp.o

utils/print_help.i: utils/print_help.cpp.i
.PHONY : utils/print_help.i

# target to preprocess a source file
utils/print_help.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/utils/print_help.cpp.i
.PHONY : utils/print_help.cpp.i

utils/print_help.s: utils/print_help.cpp.s
.PHONY : utils/print_help.s

# target to generate assembly for a file
utils/print_help.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/HSV_Mapper.dir/build.make CMakeFiles/HSV_Mapper.dir/utils/print_help.cpp.s
.PHONY : utils/print_help.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... HSV_Mapper"
	@echo "... glad"
	@echo "... glfw"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
	@echo "... src/VertexBuffer.o"
	@echo "... src/VertexBuffer.i"
	@echo "... src/VertexBuffer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... utils/config_utils.o"
	@echo "... utils/config_utils.i"
	@echo "... utils/config_utils.s"
	@echo "... utils/load_shader.o"
	@echo "... utils/load_shader.i"
	@echo "... utils/load_shader.s"
	@echo "... utils/log_utils.o"
	@echo "... utils/log_utils.i"
	@echo "... utils/log_utils.s"
	@echo "... utils/parse_utils.o"
	@echo "... utils/parse_utils.i"
	@echo "... utils/parse_utils.s"
	@echo "... utils/print_help.o"
	@echo "... utils/print_help.i"
	@echo "... utils/print_help.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

