#ifndef HSV_MAPPER_CONSTS_H
#define HSV_MAPPER_CONSTS_H

enum ExitReason: int {
    SUCCESS, // 0
    COMP_FLAGS_UNREADABLE,
    GLAD_INIT_FAILURE,
    GLFW_INIT_FAILURE,
    GLFW_WINDOW_INIT_FAILURE,
    FRAMEBUFFER_CREATION_FAILURE,
    IMAGE_NOT_FOUND,
    IMAGE_LOAD_ERR,
    ARG_PARSE_EXIT,
    MAX_VIEWPORT_SIZE_EXCEEDED,
    SHADER_COMPILATION_FAILED
};

const char *COMP_NAME_MAP[] = {"hue", "sat", "val", "rgb", "red", "green", "blue"};

#endif //HSV_MAPPER_CONSTS_H
