//
// Created by Cale on 5/20/2022.
//

#ifndef HSV_MAPPER_CONSTS_H
#define HSV_MAPPER_CONSTS_H

enum ExitReason {
    SUCCESS, // 0
    COMP_FLAGS_UNREADABLE,
    GLAD_INIT_FAILURE,
    GLFW_INIT_FAILURE,
    GLFW_WINDOW_INIT_FAILURE,
    FRAMEBUFFER_CREATION_FAILURE,
    IMAGE_NOT_FOUND,
    IMAGE_LOAD_ERR,
    ARG_PARSE_EXIT,
    COMPONENTS_EXCEEDS_DIMENSIONS,
    MAX_VIEWPORT_SIZE_EXCEEDED
};

#endif //HSV_MAPPER_CONSTS_H
